-- 감사로그 테이블 Oracle 시퀀스 DDL
-- AuditLogIdGenerator 채번 규칙: TPRMPP_{테이블명} → SQ_{테이블명}_1
-- ddl-auto=update는 @Entity 테이블만 자동 생성하므로 이 스크립트를 수동 실행 필요
--
-- 실행 대상 DB: Oracle XEPDB1 (ITPAPP 사용자)
-- 실행 방법: sqlplus ITPAPP@XEPDB1 @audit_log_sequences_ddl.sql

-- 정보화실무협의회 기본정보 변경 로그 (TPRMPP_BASCTL)
CREATE SEQUENCE SQ_TPRMPP_BASCTL_1
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 예산 변경 로그 (TPRMPP_BBUGTL)
CREATE SEQUENCE SQ_TPRMPP_BBUGTL_1
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 타당성 자체점검 변경 로그 (TPRMPP_BCHKLL)
CREATE SEQUENCE SQ_TPRMPP_BCHKLL_1
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 협의회 평가위원 변경 로그 (TPRMPP_BCMMTL)
CREATE SEQUENCE SQ_TPRMPP_BCMMTL_1
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 전산관리비 변경 로그 (TPRMPP_BCOSTL)
CREATE SEQUENCE SQ_TPRMPP_BCOSTL_1
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 평가위원 평가의견 변경 로그 (TPRMPP_BEVALL)
CREATE SEQUENCE SQ_TPRMPP_BEVALL_1
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 가이드 문서 변경 로그 (TPRMPP_BGDOCL)
CREATE SEQUENCE SQ_TPRMPP_BGDOCL_1
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 정보화사업 품목 변경 로그 (TPRMPP_BITEML)
CREATE SEQUENCE SQ_TPRMPP_BITEML_1
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 성과관리 자체계획 변경 로그 (TPRMPP_BPERFL)
CREATE SEQUENCE SQ_TPRMPP_BPERFL_1
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 정보기술부문계획 변경 로그 (TPRMPP_BPLANL)
CREATE SEQUENCE SQ_TPRMPP_BPLANL_1
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 협의회 사업개요 변경 로그 (TPRMPP_BPOVWL)
CREATE SEQUENCE SQ_TPRMPP_BPOVWL_1
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 사전질의응답 변경 로그 (TPRMPP_BPQNAL)
CREATE SEQUENCE SQ_TPRMPP_BPQNAL_1
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 본회의 질의응답 변경 로그 (TPRMPP_BMQNAL) — PRD §26
CREATE SEQUENCE SQ_TPRMPP_BMQNAL_1
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 정보화사업 변경 로그 (TPRMPP_BPROJL)
CREATE SEQUENCE SQ_TPRMPP_BPROJL_1
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 요구사항 정의서 변경 로그 (TPRMPP_BRDOCL)
CREATE SEQUENCE SQ_TPRMPP_BRDOCL_1
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 문서 검토의견 변경 로그 (TPRMPP_BRIVGL)
CREATE SEQUENCE SQ_TPRMPP_BRIVGL_1
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 협의회 결과서 변경 로그 (TPRMPP_BRSLTL)
CREATE SEQUENCE SQ_TPRMPP_BRSLTL_1
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 협의회 일정 변경 로그 (TPRMPP_BSCHDL)
CREATE SEQUENCE SQ_TPRMPP_BSCHDL_1
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 단말기관리마스터 변경 로그 (TPRMPP_BTERML)
CREATE SEQUENCE SQ_TPRMPP_BTERML_1
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 신청서 마스터 변경 로그 (TPRMPP_CAPPLL)
CREATE SEQUENCE SQ_TPRMPP_CAPPLL_1
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 코드 마스터 변경 로그 (TPRMPP_CCODEL)
CREATE SEQUENCE SQ_TPRMPP_CCODEL_1
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 메뉴 변경 로그 (TPRMPP_CMENUL)
CREATE SEQUENCE SQ_TPRMPP_CMENUL_1
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 구분언어마스터 변경 로그 (TPRMPP_CLANGL)
CREATE SEQUENCE SQ_TPRMPP_CLANGL_1
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMIT;
