-- 감사로그 테이블 Oracle 시퀀스 DDL
-- AuditLogIdGenerator.resolvePostfix() 규칙: TAAABB_{POSTFIX} → S_{POSTFIX}
-- ddl-auto=update는 @Entity 테이블만 자동 생성하므로 이 스크립트를 수동 실행 필요
--
-- 실행 대상 DB: Oracle XEPDB1 (ITPAPP 사용자)
-- 실행 방법: sqlplus ITPAPP@XEPDB1 @audit_log_sequences_ddl.sql

-- 정보화실무협의회 기본정보 변경 로그 (TAAABB_BASCTL)
CREATE SEQUENCE S_BASCTL
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 예산 변경 로그 (TAAABB_BBUGTL)
CREATE SEQUENCE S_BBUGTL
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 타당성 자체점검 변경 로그 (TAAABB_BCHKLL)
CREATE SEQUENCE S_BCHKLL
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 협의회 평가위원 변경 로그 (TAAABB_BCMMTL)
CREATE SEQUENCE S_BCMMTL
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 전산관리비 변경 로그 (TAAABB_BCOSTL)
CREATE SEQUENCE S_BCOSTL
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 평가위원 평가의견 변경 로그 (TAAABB_BEVALL)
CREATE SEQUENCE S_BEVALL
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 가이드 문서 변경 로그 (TAAABB_BGDOCL)
CREATE SEQUENCE S_BGDOCL
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 정보화사업 품목 변경 로그 (TAAABB_BITEML)
CREATE SEQUENCE S_BITEML
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 성과관리 자체계획 변경 로그 (TAAABB_BPERFL)
CREATE SEQUENCE S_BPERFL
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 정보기술부문계획 변경 로그 (TAAABB_BPLANL)
CREATE SEQUENCE S_BPLANL
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 협의회 사업개요 변경 로그 (TAAABB_BPOVWL)
CREATE SEQUENCE S_BPOVWL
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 사전질의응답 변경 로그 (TAAABB_BPQNAL)
CREATE SEQUENCE S_BPQNAL
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 정보화사업 변경 로그 (TAAABB_BPROJL)
CREATE SEQUENCE S_BPROJL
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 요구사항 정의서 변경 로그 (TAAABB_BRDOCL)
CREATE SEQUENCE S_BRDOCL
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 문서 검토의견 변경 로그 (TAAABB_BRIVGL)
CREATE SEQUENCE S_BRIVGL
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 협의회 결과서 변경 로그 (TAAABB_BRSLTL)
CREATE SEQUENCE S_BRSLTL
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 협의회 일정 변경 로그 (TAAABB_BSCHDL)
CREATE SEQUENCE S_BSCHDL
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 단말기관리마스터 변경 로그 (TAAABB_BTERML)
CREATE SEQUENCE S_BTERML
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 신청서 마스터 변경 로그 (TAAABB_CAPPLL)
CREATE SEQUENCE S_CAPPLL
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 코드 마스터 변경 로그 (TAAABB_CCODEL)
CREATE SEQUENCE S_CCODEL
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMIT;
