SET LINESIZE 200
SET PAGESIZE 50
COL ENO FORMAT A12
COL VLR_TC FORMAT A8
COL CNFM_YN FORMAT A8
SELECT ENO, VLR_TC, CNFM_YN FROM TPRMPP_BCMMTM
WHERE ASCT_ID='ASCT-2026-0403' AND DEL_YN='N'
ORDER BY ENO;
EXIT;
