SET PAGES 50 LINES 200 FEEDBACK OFF;
PROMPT === CFILEM 최대 FL_MNG_NO 5건 ===
SELECT FL_MNG_NO FROM (
  SELECT FL_MNG_NO FROM TAAABB_CFILEM ORDER BY FL_MNG_NO DESC
) WHERE ROWNUM <= 5;
PROMPT === S_FL 다음값 (조회 후 1 증가) ===
SELECT S_FL.NEXTVAL AS NEXT FROM DUAL;
PROMPT === LAST_NUMBER (시퀀스 메타) ===
SELECT SEQUENCE_NAME, LAST_NUMBER, INCREMENT_BY, CACHE_SIZE FROM USER_SEQUENCES WHERE SEQUENCE_NAME='S_FL';
EXIT;
