SET LINESIZE 200
SET PAGESIZE 50
COL ENO FORMAT A10
COL VLR_TC FORMAT A8

PROMPT === 협의회 상태 ===
SELECT ASCT_ID, ASCT_STS_C FROM TPRMPP_BASCTM WHERE ASCT_ID='ASCT-2026-0403';

PROMPT === 평가 대상 위원 (간사 003 제외) ===
SELECT ENO, VLR_TC FROM TPRMPP_BCMMTM
WHERE ASCT_ID='ASCT-2026-0403' AND DEL_YN='N' AND VLR_TC <> '003'
ORDER BY VLR_TC, ENO;

PROMPT === 기존 평가의견 수 ===
SELECT COUNT(*) AS EVAL_COUNT FROM TPRMPP_BEVALM
WHERE ASCT_ID='ASCT-2026-0403' AND DEL_YN='N';

EXIT;
