-- BMQNAL 시퀀스 신규 생성 (PRD §26)
-- AuditLogIdGenerator는 SQ_{테이블명}_1 형식으로 시퀀스 조회
-- 이전에 잘못 만든 S_BMQNAL은 미사용이므로 같이 정리합니다.
CREATE SEQUENCE SQ_TPRMPP_BMQNAL_1
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 미사용 S_BMQNAL 제거 (PRD §26 — 첫 시도에서 잘못된 접두사로 만든 잔재)
DROP SEQUENCE S_BMQNAL;

COMMIT;

SELECT SEQUENCE_NAME FROM USER_SEQUENCES WHERE SEQUENCE_NAME IN ('SQ_TPRMPP_BMQNAL_1','S_BMQNAL');

EXIT;
