SET LINESIZE 200
SET PAGESIZE 50
COL COLUMN_NAME FORMAT A30
COL DATA_TYPE FORMAT A20
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'TAAABB_BEVALM'
ORDER BY COLUMN_ID;
EXIT;
