SET DEFINE OFF;
SET SERVEROUTPUT ON;
WHENEVER SQLERROR CONTINUE;
BEGIN
    FOR r IN (
        SELECT tc.TABLE_NAME
        FROM USER_TAB_COLUMNS tc
        WHERE tc.COLUMN_NAME = 'CHG_TP'
    ) LOOP
        BEGIN
            EXECUTE IMMEDIATE 'ALTER TABLE ' || r.TABLE_NAME || ' DROP COLUMN CHG_TP';
            DBMS_OUTPUT.PUT_LINE('Dropped CHG_TP from ' || r.TABLE_NAME);
        EXCEPTION WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('FAIL ' || r.TABLE_NAME || ': ' || SQLERRM);
        END;
    END LOOP;
END;
/
COMMIT;
EXIT;
