-- ============================================================
-- PRD_c_20260518 #1: 협의회 20개 테이블 DROP (스키마 재생성용)
-- 백엔드 재기동 시 ddl-auto=update가 새 스키마로 CREATE TABLE 자동 실행
-- 영향: 협의회 데이터(ASCT-* 전체) 초기화 — 테스트 환경 전용
-- PRD §26에서 추가된 BMQNAM/BMQNAL(주요 Q&A) 포함
-- ============================================================
SET DEFINE OFF;
WHENEVER SQLERROR CONTINUE;

DROP TABLE TPRMPP_BASCTL CASCADE CONSTRAINTS;
DROP TABLE TPRMPP_BASCTM CASCADE CONSTRAINTS;
DROP TABLE TPRMPP_BCHKLC CASCADE CONSTRAINTS;
DROP TABLE TPRMPP_BCHKLL CASCADE CONSTRAINTS;
DROP TABLE TPRMPP_BCMMTL CASCADE CONSTRAINTS;
DROP TABLE TPRMPP_BCMMTM CASCADE CONSTRAINTS;
DROP TABLE TPRMPP_BEVALL CASCADE CONSTRAINTS;
DROP TABLE TPRMPP_BEVALM CASCADE CONSTRAINTS;
DROP TABLE TPRMPP_BMQNAL CASCADE CONSTRAINTS;
DROP TABLE TPRMPP_BMQNAM CASCADE CONSTRAINTS;
DROP TABLE TPRMPP_BPERFL CASCADE CONSTRAINTS;
DROP TABLE TPRMPP_BPERFM CASCADE CONSTRAINTS;
DROP TABLE TPRMPP_BPOVWL CASCADE CONSTRAINTS;
DROP TABLE TPRMPP_BPOVWM CASCADE CONSTRAINTS;
DROP TABLE TPRMPP_BPQNAL CASCADE CONSTRAINTS;
DROP TABLE TPRMPP_BPQNAM CASCADE CONSTRAINTS;
DROP TABLE TPRMPP_BRSLTL CASCADE CONSTRAINTS;
DROP TABLE TPRMPP_BRSLTM CASCADE CONSTRAINTS;
DROP TABLE TPRMPP_BSCHDL CASCADE CONSTRAINTS;
DROP TABLE TPRMPP_BSCHDM CASCADE CONSTRAINTS;

COMMIT;
EXIT;
