-- ============================================================
-- PRD_c_20260518 #1: 협의회 18개 테이블 DROP (스키마 재생성용)
-- 백엔드 재기동 시 ddl-auto=update가 새 스키마로 CREATE TABLE 자동 실행
-- 영향: 협의회 데이터(ASCT-* 전체) 초기화 — 테스트 환경 전용
-- ============================================================
SET DEFINE OFF;
WHENEVER SQLERROR CONTINUE;

DROP TABLE TAAABB_BASCTL CASCADE CONSTRAINTS;
DROP TABLE TAAABB_BASCTM CASCADE CONSTRAINTS;
DROP TABLE TAAABB_BCHKLC CASCADE CONSTRAINTS;
DROP TABLE TAAABB_BCHKLL CASCADE CONSTRAINTS;
DROP TABLE TAAABB_BCMMTL CASCADE CONSTRAINTS;
DROP TABLE TAAABB_BCMMTM CASCADE CONSTRAINTS;
DROP TABLE TAAABB_BEVALL CASCADE CONSTRAINTS;
DROP TABLE TAAABB_BEVALM CASCADE CONSTRAINTS;
DROP TABLE TAAABB_BPERFL CASCADE CONSTRAINTS;
DROP TABLE TAAABB_BPERFM CASCADE CONSTRAINTS;
DROP TABLE TAAABB_BPOVWL CASCADE CONSTRAINTS;
DROP TABLE TAAABB_BPOVWM CASCADE CONSTRAINTS;
DROP TABLE TAAABB_BPQNAL CASCADE CONSTRAINTS;
DROP TABLE TAAABB_BPQNAM CASCADE CONSTRAINTS;
DROP TABLE TAAABB_BRSLTL CASCADE CONSTRAINTS;
DROP TABLE TAAABB_BRSLTM CASCADE CONSTRAINTS;
DROP TABLE TAAABB_BSCHDL CASCADE CONSTRAINTS;
DROP TABLE TAAABB_BSCHDM CASCADE CONSTRAINTS;

COMMIT;
EXIT;
