SET DEFINE OFF;
SET SERVEROUTPUT ON;
WHENEVER SQLERROR CONTINUE;
BEGIN
    FOR r IN (
        SELECT TABLE_NAME FROM USER_TAB_COLUMNS
        WHERE COLUMN_NAME = 'CHG_TC' AND NULLABLE = 'Y'
    ) LOOP
        BEGIN
            EXECUTE IMMEDIATE 'UPDATE ' || r.TABLE_NAME || ' SET CHG_TC = ''U'' WHERE CHG_TC IS NULL';
            EXECUTE IMMEDIATE 'ALTER TABLE ' || r.TABLE_NAME || ' MODIFY CHG_TC NOT NULL';
            DBMS_OUTPUT.PUT_LINE('Enforced NOT NULL on ' || r.TABLE_NAME || '.CHG_TC');
        EXCEPTION WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('FAIL ' || r.TABLE_NAME || ': ' || SQLERRM);
        END;
    END LOOP;
END;
/
COMMIT;
EXIT;
