SET DEFINE OFF;
SET SERVEROUTPUT ON;
WHENEVER SQLERROR CONTINUE;

-- S_APF: APF_MNG_NO 채번 (CAPPLM 결재신청서 PK)
DECLARE
    v_max NUMBER;
BEGIN
    BEGIN
        EXECUTE IMMEDIATE 'DROP SEQUENCE S_APF';
    EXCEPTION WHEN OTHERS THEN NULL;
    END;
    SELECT NVL(MAX(TO_NUMBER(REGEXP_SUBSTR(APF_MNG_NO, '\d+$'))), 0) INTO v_max FROM TPRMPP_CAPPLM;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE S_APF START WITH ' || (v_max + 1) || ' INCREMENT BY 1 NOCACHE NOCYCLE';
END;
/

-- S_QTN: 사전질의 QTN_ID 채번
BEGIN
    BEGIN
        EXECUTE IMMEDIATE 'DROP SEQUENCE S_QTN';
    EXCEPTION WHEN OTHERS THEN NULL;
    END;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE S_QTN START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
END;
/

COMMIT;
EXIT;
