-- ccmmtm.CMMT_CONE: CLOB → VARCHAR2(4000) 마이그레이션
SET DEFINE OFF;
SET SERVEROUTPUT ON;
WHENEVER SQLERROR CONTINUE;
DECLARE v_type VARCHAR2(30);
BEGIN
    SELECT DATA_TYPE INTO v_type FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'TAAABB_CCMMTM' AND COLUMN_NAME = 'CMMT_CONE';
    IF v_type = 'VARCHAR2' THEN
        DBMS_OUTPUT.PUT_LINE('Already VARCHAR2');
    ELSE
        EXECUTE IMMEDIATE 'ALTER TABLE TAAABB_CCMMTM ADD CMMT_CONE_TMP VARCHAR2(4000)';
        EXECUTE IMMEDIATE 'UPDATE TAAABB_CCMMTM SET CMMT_CONE_TMP = DBMS_LOB.SUBSTR(CMMT_CONE, 4000, 1)';
        EXECUTE IMMEDIATE 'ALTER TABLE TAAABB_CCMMTM DROP COLUMN CMMT_CONE';
        EXECUTE IMMEDIATE 'ALTER TABLE TAAABB_CCMMTM RENAME COLUMN CMMT_CONE_TMP TO CMMT_CONE';
        DBMS_OUTPUT.PUT_LINE('Converted CCMMTM.CMMT_CONE CLOB -> VARCHAR2(4000)');
    END IF;
END;
/
COMMIT;
EXIT;
