UPDATE TPRMPP_BCMMTM
   SET CNFM_YN = 'Y',
       LST_CHG_DTM = SYSDATE,
       LST_CHG_USID = 'SYSTEM'
 WHERE ASCT_ID = 'ASCT-2026-0403'
   AND ENO = 'K230035'
   AND DEL_YN = 'N';
COMMIT;

SET LINESIZE 200
COL ENO FORMAT A12
COL CNFM_YN FORMAT A8
SELECT ENO, CNFM_YN FROM TPRMPP_BCMMTM
WHERE ASCT_ID='ASCT-2026-0403' AND DEL_YN='N'
ORDER BY ENO;
EXIT;
