SET DEFINE OFF;
SET SERVEROUTPUT ON;
WHENEVER SQLERROR CONTINUE;
DROP SEQUENCE S_FL;
DECLARE
    v_max NUMBER;
BEGIN
    SELECT NVL(MAX(TO_NUMBER(REGEXP_SUBSTR(FL_MNG_NO, '\d+$'))), 0) INTO v_max FROM TAAABB_CFILEM;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE S_FL START WITH ' || (v_max + 1) || ' INCREMENT BY 1 NOCACHE NOCYCLE';
    DBMS_OUTPUT.PUT_LINE('S_FL recreated starting at ' || (v_max + 1));
END;
/
COMMIT;
EXIT;
