-- S_FL 안전 재설정: MAX(FL_MNG_NO 숫자)+1000 점프 + CACHE 20
SET DEFINE OFF;
SET SERVEROUTPUT ON;
WHENEVER SQLERROR CONTINUE;
DROP SEQUENCE S_FL;
DECLARE
    v_start NUMBER;
BEGIN
    SELECT NVL(MAX(TO_NUMBER(REGEXP_SUBSTR(FL_MNG_NO, '\d+$'))), 0) + 1000 INTO v_start FROM TPRMPP_CFILEM;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE S_FL START WITH ' || v_start || ' INCREMENT BY 1 CACHE 20 NOCYCLE';
    DBMS_OUTPUT.PUT_LINE('S_FL recreated starting at ' || v_start);
END;
/
COMMIT;
EXIT;
