-- PRD §31: ASCT_STS_C CDVA 012/013 라벨 스왑
--   012: 완료 → 결과보고 결재 중
--   013: 결과보고 결재 중 → 완료
UPDATE TPRMPP_CCODEM
   SET CDVA_NM = '결과보고 결재 중',
       CO_CDVA_SPS = '결과보고 결재 중',
       LST_CHG_DTM = SYSDATE,
       LST_CHG_USID = 'SYSTEM'
 WHERE CO_C_ID_NM = 'ASCT_STS_C' AND CDVA_ID = '012';

UPDATE TPRMPP_CCODEM
   SET CDVA_NM = '완료',
       CO_CDVA_SPS = '완료',
       LST_CHG_DTM = SYSDATE,
       LST_CHG_USID = 'SYSTEM'
 WHERE CO_C_ID_NM = 'ASCT_STS_C' AND CDVA_ID = '013';

COMMIT;

SET LINESIZE 200
COL CDVA_ID FORMAT A6
COL CDVA_NM FORMAT A30
SELECT CDVA_ID, CDVA_NM FROM TPRMPP_CCODEM
WHERE CO_C_ID_NM='ASCT_STS_C' AND CDVA_ID IN ('012','013')
ORDER BY CDVA_ID;

EXIT;
