-- PRD §31: ASCT_STS_C CDVA 012/013 라벨 스왑
--   012: 완료 → 결과보고 결재 중
--   013: 결과보고 결재 중 → 완료
UPDATE TAAABB_CCODEM
   SET CDVA_NM = '결과보고 결재 중',
       CDVA_DTL = '결과보고 결재 중',
       LST_CHG_DTM = SYSDATE,
       LST_CHG_USID = 'SYSTEM'
 WHERE C_ID = 'ASCT_STS_C' AND CDVA = '012';

UPDATE TAAABB_CCODEM
   SET CDVA_NM = '완료',
       CDVA_DTL = '완료',
       LST_CHG_DTM = SYSDATE,
       LST_CHG_USID = 'SYSTEM'
 WHERE C_ID = 'ASCT_STS_C' AND CDVA = '013';

COMMIT;

SET LINESIZE 200
COL CDVA FORMAT A6
COL CDVA_NM FORMAT A30
SELECT CDVA, CDVA_NM FROM TAAABB_CCODEM
WHERE C_ID='ASCT_STS_C' AND CDVA IN ('012','013')
ORDER BY CDVA;

EXIT;
