SET PAGES 50 LINES 200 FEEDBACK OFF;
PROMPT === DT 컬럼 타입 확인 (VARCHAR2(8) 이어야 함) ===
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH
FROM USER_TAB_COLUMNS
WHERE COLUMN_NAME IN ('CNRC_DT', 'DSD_DT', 'MSM_STT_DT', 'MSM_END_DT')
ORDER BY TABLE_NAME, COLUMN_NAME;

PROMPT === CHG_TC NOT NULL 확인 (모든 *L 테이블) ===
SELECT TABLE_NAME, NULLABLE
FROM USER_TAB_COLUMNS
WHERE COLUMN_NAME = 'CHG_TC'
ORDER BY TABLE_NAME;

PROMPT === 새 협의회 일정 DB 값 (yyyyMMdd 형식 확인) ===
SELECT ASCT_ID, ASCT_STS_C, CNRC_DT, CNRC_TM, CNRC_PLC_NM
FROM TAAABB_BASCTM WHERE ASCT_ID = 'ASCT-2026-0402';

PROMPT === KPN_TC 저장값 확인 ===
SELECT ASCT_ID, KPN_TC FROM TAAABB_BPOVWM WHERE ASCT_ID = 'ASCT-2026-0402';

EXIT;
