-- 접미사 표준화 검증: 신규 CO_C_ID 건수 + 구 CO_C_ID 잔존 확인
SET LINESIZE 200
SET PAGESIZE 50
COLUMN CO_C_ID FORMAT A12
COLUMN CDVA_ID FORMAT A6
COLUMN CDVA_NM FORMAT A30

PROMPT === 신규 CO_C_ID 건수 ===
SELECT CO_C_ID, COUNT(*) AS CNT
FROM TPRMPP_CCODEM
WHERE CO_C_ID IN ('ASCT_STS_C', 'DBR_TC', 'VLR_TC', 'CKG_ITM_C', 'KPN_TC')
  AND DEL_YN = 'N'
GROUP BY CO_C_ID
ORDER BY CO_C_ID;

PROMPT === 구 CO_C_ID 잔존 여부 (모두 0이어야 함) ===
SELECT CO_C_ID, COUNT(*) AS REMAINING
FROM TPRMPP_CCODEM
WHERE CO_C_ID IN ('ASCT_STS', 'DBR_TP', 'VLR_TP', 'CKG_ITM')
GROUP BY CO_C_ID
ORDER BY CO_C_ID;

PROMPT === DBR_TC 샘플 ===
SELECT CO_C_ID, CDVA_ID, CDVA_NM FROM TPRMPP_CCODEM
WHERE CO_C_ID = 'DBR_TC' AND DEL_YN = 'N' ORDER BY CDVA_ID;

EXIT;
