-- 접미사 표준화 검증: 신규 C_ID 건수 + 구 C_ID 잔존 확인
SET LINESIZE 200
SET PAGESIZE 50
COLUMN C_ID FORMAT A12
COLUMN CDVA FORMAT A6
COLUMN CDVA_NM FORMAT A30

PROMPT === 신규 C_ID 건수 ===
SELECT C_ID, COUNT(*) AS CNT
FROM TAAABB_CCODEM
WHERE C_ID IN ('ASCT_STS_C', 'DBR_TC', 'VLR_TC', 'CKG_ITM_C', 'KPN_TC')
  AND DEL_YN = 'N'
GROUP BY C_ID
ORDER BY C_ID;

PROMPT === 구 C_ID 잔존 여부 (모두 0이어야 함) ===
SELECT C_ID, COUNT(*) AS REMAINING
FROM TAAABB_CCODEM
WHERE C_ID IN ('ASCT_STS', 'DBR_TP', 'VLR_TP', 'CKG_ITM')
GROUP BY C_ID
ORDER BY C_ID;

PROMPT === DBR_TC 샘플 ===
SELECT C_ID, CDVA, CDVA_NM FROM TAAABB_CCODEM
WHERE C_ID = 'DBR_TC' AND DEL_YN = 'N' ORDER BY CDVA;

EXIT;
