###############################
#    Web-Agent \uD658\uACBD \uC124\uC815
###############################
AUTH_URL = 10.8.99.170:20080
AGENT_ID  = 5
REQUEST_DATA = id

###############################
#    Agent Page
###############################
BUSINESS_PAGE = /sso/Business
LOGOUT_PAGE = /sso/Logout
ERROR_PAGE = /sso/Error
EXCEPTION_PAGE = /exception

###############################
#    HttpClient Timeout \uC124\uC815
###############################
connectionTimeout = 5000
soTimeout = 5000


###############################
#    ISign+ API URL
###############################
CHECK_SERVER_URL = /openapi/checkserver
TOKEN_AUTHORIZATION_URL = /token/authorization
SAVE_TOKEN_URL = /token/saveToken.html
AUTH_LOGIN_PAGE = /login.html
AUTH_LOGOUT_PAGE = /logout.html
SERVICE_ERR_PAGE = /serviceError.html