-- Tiptap 예산 변수 카테고리의 운영 데이터 분류를 검증합니다.
-- SQL*Plus에서 재실행할 수 있으며 SQL 오류가 발생하면 비정상 종료합니다.

WHENEVER SQLERROR EXIT SQL.SQLCODE
WHENEVER OSERROR EXIT FAILURE

SET ECHO OFF
SET FEEDBACK ON
SET HEADING ON
SET LINESIZE 220
SET PAGESIZE 1000
SET TRIMSPOOL ON
SET VERIFY OFF

DEFINE BSE_YY = '2026'

ALTER SESSION SET CURRENT_SCHEMA = ITPOWN;

COLUMN CATEGORY FORMAT A20
COLUMN ITEM_COUNT FORMAT 9999999990
COLUMN REQUEST_SUM FORMAT 9999999999999999999999999990
COLUMN IOE_C FORMAT A20
COLUMN C_TP FORMAT A30
COLUMN UNMAPPED_GROUP_COUNT FORMAT 9999999990

PROMPT
PROMPT [Tiptap 예산 카테고리 집계]
PROMPT 기준연도: &BSE_YY

WITH ITEMS AS (
    SELECT P.BSE_YY,
           I.GCL_MNG_NO,
           I.AMT,
           I.IOE_C,
           C.CO_C_INTN_NM AS C_TP
      FROM TPRMPP_BPROJM P
      JOIN TPRMPP_BITEMM I
        ON I.ABUS_MNG_NO = P.ABUS_MNG_NO
       AND I.FNT_TB_CRY_SNO = P.SNO
       AND I.DEL_YN = 'N'
       AND I.LST_YN = 'Y'
      LEFT JOIN TPRMPP_CCODEM C
        ON C.CO_C_ID_NM = 'IOE_C'
       AND C.CDVA_ID = I.IOE_C
       AND C.DEL_YN = 'N'
     WHERE P.BSE_YY = '&BSE_YY'
       AND P.DEL_YN = 'N'
       AND P.LST_YN = 'Y'
)
SELECT 'IT_BUDGET' CATEGORY,
       COUNT(*) ITEM_COUNT,
       NVL(SUM(AMT), 0) REQUEST_SUM
  FROM ITEMS
UNION ALL
SELECT 'CAP_BUDGET',
       COUNT(*),
       NVL(SUM(AMT), 0)
  FROM ITEMS
 WHERE C_TP IN ('IOE_DVC', 'IOE_HW', 'IOE_SW', 'IOE_CPIT')
UNION ALL
SELECT 'OPEX',
       COUNT(*),
       NVL(SUM(AMT), 0)
  FROM ITEMS
 WHERE C_TP IN ('IOE_IDR', 'IOE_SEVS', 'IOE_XPN', 'IOE_LEAFE');

PROMPT
PROMPT [미매핑 코드 목록]

WITH ITEMS AS (
    SELECT I.AMT,
           I.IOE_C,
           C.CO_C_INTN_NM AS C_TP
      FROM TPRMPP_BPROJM P
      JOIN TPRMPP_BITEMM I
        ON I.ABUS_MNG_NO = P.ABUS_MNG_NO
       AND I.FNT_TB_CRY_SNO = P.SNO
       AND I.DEL_YN = 'N'
       AND I.LST_YN = 'Y'
      LEFT JOIN TPRMPP_CCODEM C
        ON C.CO_C_ID_NM = 'IOE_C'
       AND C.CDVA_ID = I.IOE_C
       AND C.DEL_YN = 'N'
     WHERE P.BSE_YY = '&BSE_YY'
       AND P.DEL_YN = 'N'
       AND P.LST_YN = 'Y'
)
SELECT NVL(IOE_C, '<NULL>') IOE_C,
       NVL(C_TP, '<NULL>') C_TP,
       COUNT(*) ITEM_COUNT,
       NVL(SUM(AMT), 0) REQUEST_SUM
  FROM ITEMS
 WHERE C_TP IS NULL
    OR C_TP NOT IN (
       'IOE_DVC', 'IOE_HW', 'IOE_SW', 'IOE_CPIT',
       'IOE_IDR', 'IOE_SEVS', 'IOE_XPN', 'IOE_LEAFE'
   )
 GROUP BY IOE_C, C_TP
 ORDER BY IOE_C, C_TP;

PROMPT
PROMPT [미매핑 그룹 수]

WITH ITEMS AS (
    SELECT I.IOE_C,
           C.CO_C_INTN_NM AS C_TP
      FROM TPRMPP_BPROJM P
      JOIN TPRMPP_BITEMM I
        ON I.ABUS_MNG_NO = P.ABUS_MNG_NO
       AND I.FNT_TB_CRY_SNO = P.SNO
       AND I.DEL_YN = 'N'
       AND I.LST_YN = 'Y'
      LEFT JOIN TPRMPP_CCODEM C
        ON C.CO_C_ID_NM = 'IOE_C'
       AND C.CDVA_ID = I.IOE_C
       AND C.DEL_YN = 'N'
     WHERE P.BSE_YY = '&BSE_YY'
       AND P.DEL_YN = 'N'
       AND P.LST_YN = 'Y'
),
UNMAPPED AS (
    SELECT IOE_C, C_TP
      FROM ITEMS
     WHERE C_TP IS NULL
        OR C_TP NOT IN (
           'IOE_DVC', 'IOE_HW', 'IOE_SW', 'IOE_CPIT',
           'IOE_IDR', 'IOE_SEVS', 'IOE_XPN', 'IOE_LEAFE'
       )
     GROUP BY IOE_C, C_TP
)
SELECT COUNT(*) UNMAPPED_GROUP_COUNT
  FROM UNMAPPED;

EXIT SUCCESS
